training:
  model_name: "latent-action-15-4"
  dataset_name: "minigrid-1000-20.pt"
  num_epochs: 200
  batch_size: 64
  train_ratio: 0.8
  lr: 0.0001
  beta: 0.1
model:
  type: "LatentAction"
  state_dim: 16
  num_classes: 16
  action_dim: 4
  action_classes: 4
  encoder_layers: [512, 256]
  decoder_layers: [512, 512]
  deterministic_dim: 128
  include_initial_deterministic: true
  latent_handler:
    type: "CategoricalLatentHandler"
    straight_through: true
    temperature: 1.0